### ISSUE TITLE
Fly#C - False flag running across gaps

### ISSUE THREAD

**Issue by Spuckwaffel** [thedarthonian/KarmaAC-Issues#3]
**What unexpected behaviour is happening? (Please include Check#ABC)**

**To Reproduce**
1. Build something like in the video
2. 
3. 
4. 

**Expected behaviour**
You shoudlnt get flagged for fly#C

**Screenshots/Videos**
https://youtu.be/IEpbZW1rTss

https://youtu.be/rLPRguJNdf4

**Client:**
 - none

**Additional context**
Fly#C is the issue

**Comment by Prophateee** [comment]
fixed
