### ISSUE TITLE
Fly#C - False flag falling backwards off block

### ISSUE THREAD

**Issue by Spuckwaffel** [thedarthonian/KarmaAC-Issues#4]
**What unexpected behaviour is happening? (Please include Check#ABC)**

**To Reproduce**
1. Walk up and down full blocks
2. 
3. 
4. 

**Expected behaviour**
Nothing should happen

**Screenshots/Videos**
https://youtu.be/6C1DR7tAIfc

**Client:**
 - None

**Additional context**
Speed#B and Fly#C

**Comment by Prophateee** [comment]
fixed
