### ISSUE TITLE
Speed#F - False flag on respawn after death

### ISSUE THREAD

**Issue by Spuckwaffel** [thedarthonian/KarmaAC-Issues#6]
**What unexpected behaviour is happening? (Please include Check#ABC)**

**To Reproduce**
1. Die in Lava
2. Respawn 
3. 
4. 

**Expected behaviour**
Nothing should happen

**Screenshots/Videos**
https://youtu.be/wHJShOK10JY

**Client:**
 - None

**Additional context**
Speed#F flag

**Comment by thedarthonian** [comment]
Fixed
